Repository missionpinball/mpf-mc, pull requests merged in 2019-07, with the labels that each got.

#377 add token to slide_player + unit and integration tests
  mpfmc/config_players/slide_player.py
  mpfmc/integration/machine_files/widgets_and_slides/config/config.yaml
  mpfmc/integration/machine_files/widgets_and_slides/shows/slide_show.yaml
  mpfmc/integration/test_WidgetsAndSlides.py
  mpfmc/tests/machine_files/slide_player/config/test_slide_player.yaml
  mpfmc/tests/test_SlidePlayer.py
Labels: new feature

#378 Fix events on sounds
  mpfmc/assets/sound.py
  mpfmc/config_players/plugins/sound_player.py
  mpfmc/config_players/sound_player.py
  mpfmc/integration/machine_files/audio/config/config.yaml
  mpfmc/integration/test_Audio.py
  mpfmc/tests/machine_files/audio/config/test_audio.yaml
  mpfmc/tests/test_Audio.py
Labels: bug

#381 move parse_conditional_template out of hot loop
  mpfmc/config_players/slide_player.py
  mpfmc/integration/machine_files/widgets_and_slides/config/config.yaml
  mpfmc/integration/machine_files/widgets_and_slides/modes/mode7/config/mode7.yaml
  mpfmc/integration/test_BasicGame.py
  mpfmc/integration/test_WidgetsAndSlides.py
  mpfmc/tests/MpfIntegrationTestCase.py
  mpfmc/tests/test_SlidePlayer.py
Labels: code refactor

#382 Known-good tests for conditional slides
  mpfmc/config_players/slide_player.py
  mpfmc/tests/machine_files/slide_player/config/test_slide_player.yaml
  mpfmc/tests/test_SlidePlayer.py
Labels: bug
